Add real validations step

diff --git a/.github/workflows/ci-build-test.yaml b/.github/workflows/ci-build-test.yaml
--- a/.github/workflows/ci-build-test.yaml
+++ b/.github/workflows/ci-build-test.yaml
@@ -27,7 +27,22 @@ jobs:
         run: docker run -d -p 5000:5000 --name prod-container cicd-prod
       
       - name: Wait for app
-        run: sleep 5
+        run: |
+          for i in {1..10}; do
+            if curl -s http://localhost:5000; then
+              echo "App is up"
+              exit 0
+            fi
+              echo "Waiting for app..."
+              sleep 2
+          done
+
+          echo "App failed to start"
+          exit 1
       
-      - name: Fake test
-        run: echo "all test passed successfully"
+      - name: Real health check
+        run: curl -f http://localhost:5000
+
+      - name: Clean up
+        if: always()
+        run: docker stop prod-container && docker rm prod-container
